// Action Types
// CART MANAGEMENT
export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

// FILTER MANAGEMENT
export const SET_BRAND_FILTERS = 'SET_BRAND_FILTERS';
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_GENDER_FILTER = 'SET_GENDER_FILTER';
export const APPLY_FILTERS = 'APPLY_FILTERS';

// WISHLIST MANAGEMENT
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

// Product Detail
export const STORE_PRODUCT_DETAILS = 'STORE_PRODUCT_DETAILS';

// Search Product
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_MATCHING_PRODUCTS = 'SET_MATCHING_PRODUCTS';
