// Action Types
// CART MANAGEMENT
export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

// FILTER MANAGEMENT
export const SET_BRAND_FILTERS = 'SET_BRAND_FILTERS';
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_GENDER_FILTER = 'SET_GENDER_FILTER';
export const APPLY_FILTERS = 'APPLY_FILTERS';
